
Characteristics = {
    "SalesMan": {
        "CUSTOMER": {
            1: ["select", ["C_FIRST", "C_LAST", "C_PHONE", "C_DATA"], ["C_W_ID", "C_D_ID", "C_ID"]],
            2: ["select", ["C_STREET_1", "C_STREET_2", "C_CITY", "C_STATE", "C_ZIP"], ["C_W_ID", "C_D_ID", "C_ID"]],
            3: ["select", ["C_DISCOUNT"], ["C_W_ID", "C_D_ID", "C_ID"]],
            4: ["select", ["C_BALANCE"], ["C_W_ID", "C_D_ID", "C_ID"]],
            5: ["select", ["C_CREDIT", "C_CREDIT_LIM"], ["C_W_ID", "C_D_ID", "C_ID"]],
            6: ["select", ["H_DATE"], ["C_W_ID", "C_D_ID", "C_ID"]],
            7: ["insert",["C_SINCE",], ["C_ID", "C_D_ID", "C_W_ID", "C_FIRST", "C_MIDDLE", "C_LAST", "C_STREET_1", "C_STREET_2",
                    "C_CITY", "C_STATE", "C_ZIP", "C_PHONE",  "C_CREDIT", "C_CREDIT_LIM",
                    "C_DISCOUNT", "C_BALANCE", "C_YTD_PAYMENT", "C_PAYMENT_CNT", "C_DELIVERY_CNT", "C_DATA"]],
            8: ["update", [], ["C_DISCOUNT", "C_W_ID", "C_D_ID", "C_ID"]],
            9: ["update", [], ["C_CREDIT", "C_CREDIT_LIM", "C_W_ID", "C_D_ID", "C_ID"]],
            10: ["update",[], ["C_STREET_1", "C_STREET_2", "C_CITY", "C_STATE", "C_ZIP", "C_W_ID", "C_D_ID", "C_ID"]],
            11: ["delete", [], ["C_W_ID", "C_D_ID", "C_ID"]],
        },
        "ORDERS": {
            1: ["insert", ["O_ENTRY_D"], ["O_W_ID", "O_D_ID", "O_ID", "O_C_ID", "O_OL_CNT", "O_ALL_LOCAL", "O_CARRIER_ID"]],
            2: ["select", ["O_C_ID"], ["O_W_ID", "O_D_ID", "O_ID"]],
            3: ["select", ["O_W_ID", "O_D_ID"], ["O_ID"]],
            4: ["select", ["O_CARRIER_ID"], ["O_W_ID", "O_D_ID", "O_ID"]],
            5: ["select", ["O_OL_CNT"], ["O_W_ID", "O_D_ID", "O_ID"]],
            6: ["select", ["O_ID","O_ENTRY_D"], ["O_W_ID", "O_D_ID", "O_ID"]],
            7: ["update", [], ["O_CARRIER_ID", "O_W_ID", "O_D_ID", "O_ID"]],
            8: ["delete", [], ["O_W_ID", "O_D_ID", "O_ID"]],
        },
        "ORDER_LINE": {
            1: ["select", ["OL_O_ID", "OL_I_ID", "OL_QUANTITY"], ["OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
            2: ["select", ["OL_O_ID", "OL_I_ID", "OL_AMOUNT"], ["OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
            3: ["update", [], ["OL_QUANTITY", "OL_AMOUNT", "OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
            4: ["insert", ["OL_DELIVERY_D"], ["OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER", "OL_I_ID", "OL_SUPPLY_W_ID", "OL_QUANTITY",
                    "OL_AMOUNT", "OL_DIST_INFO", ]],
            5: ["update", [], ["OL_AMOUNT", "OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
            6: ["delete", [], ["OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
        },
        "HISTORY": {
            1: ["select", ["H_AMOUNT"], ["H_C_ID", "H_DATE", "H_DATE"]],
            2: ["select", ["H_DATE", "H_AMOUNT"], ["H_C_ID", "H_C_D_ID", "H_C_W_ID", "H_DATE", "H_DATE"]],
            3: ["select", ["H_DATE", "H_AMOUNT", "H_DATA"], ["H_C_ID", "H_C_D_ID", "H_C_W_ID", "H_DATE", "H_DATE"]],
            4: ["insert", ["H_DATE"], ["H_C_ID", "H_C_D_ID", "H_C_W_ID", "H_D_ID", "H_W_ID", "H_AMOUNT", "H_DATA"]],
            5: ["update", [], ["H_AMOUNT", "H_DATA", "H_C_ID", "H_C_D_ID", "H_C_W_ID"]],
            6: ["delete", [], ["H_C_ID", "H_C_D_ID", "H_C_W_ID"]],
        },
        "ITEM": {
            1: ["select", ["I_ID", "I_IM_ID"], ["I_NAME"]],
            2: ["select", ["I_PRICE", "I_DATA"], ["I_NAME"]],
            3: ["select", ["I_NAME"], ["I_ID"]],
        },
        "STOCK": {
            1: ["select", ["S_QUANTITY"], ["S_W_ID", "S_I_ID"]],
            2: ["select", ["S_ORDER_CNT"], ["S_W_ID", "S_I_ID"]],
            3: ["select", ["S_YTD"], ["S_W_ID", "S_I_ID"]],
        },
        "WAREHOUSE": {
            1: ["select", ["W_YTD"], ["W_ID"]],
            2: ["select", ["W_TAX"], ["W_ID"]],
        },
        "DISTRICT": {
            1: ["select", ["D_YTD"], ["D_ID", "D_W_ID"]],
            2: ["select", ["D_TAX"], ["D_ID", "D_W_ID"]],
        },
    },
    "WarehousesMan": {
        "STOCK": {
            1: ["select", ["S_QUANTITY"], ["S_W_ID", "S_I_ID"]],
            2: ["select", ["S_ORDER_CNT"], ["S_W_ID", "S_I_ID"]],
            3: ["select", ["S_QUANTITY", "S_DATA"], ["S_W_ID", "S_I_ID"]],
            4: ["select", ["S_I_ID", "S_QUANTITY"], ["S_W_ID"]],
            5: ["select", ["S_DIST_01", "S_DIST_02", "S_DIST_03", "S_DIST_04", "S_DIST_05",
                    "S_DIST_06", "S_DIST_07", "S_DIST_08", "S_DIST_09", "S_DIST_10"], ["S_W_ID", "S_I_ID"]],
            6: ["update", [], ["S_QUANTITY", "S_YTD", "S_ORDER_CNT",
                    "S_REMOTE_CNT", "S_DATA", "S_W_ID", "S_I_ID"]],
            7: ["update", [],[ "S_DIST_01", "S_DIST_02", "S_DIST_03", "S_DIST_04", "S_DIST_05",
                    "S_DIST_06", "S_DIST_07", "S_DIST_08", "S_DIST_09", "S_DIST_10", "S_W_ID", "S_I_ID"]],
            8: ["insert", [], ["S_W_ID", "S_I_ID", "S_QUANTITY", "S_YTD", "S_ORDER_CNT",
                                 "S_REMOTE_CNT", "S_DATA", "S_DIST_01", "S_DIST_02", "S_DIST_03",
                                 "S_DIST_04", "S_DIST_05", "S_DIST_06", "S_DIST_07", "S_DIST_08", "S_DIST_09", "S_DIST_10"]],
            9: ["delete", [], ["S_W_ID", "S_I_ID"]],
        },
        "WAREHOUSE": {
            1: ["select", ["W_STREET_1", "W_STREET_2", "W_CITY", "W_STATE", "W_ZIP"], ["W_ID"]],
            2: ["select", ["W_ID", "W_NAME"], ["W_CITY"]],
            3: ["select", ["W_ID", "W_NAME"], ["W_STATE"]],
            4: ["insert", [], ["W_ID", "W_NAME", "W_STREET_1", "W_STREET_2", "W_CITY", "W_STATE", "W_ZIP", "W_TAX", "W_YTD"]],
            5: ["update", [], ["W_NAME", "W_STREET_1", "W_STREET_2", "W_CITY", "W_STATE", "W_ZIP", "W_ID"]],
            6: ["delete", [], ["W_ID", "W_NAME"]],
        },
        "ORDERS": {
            1: ["select", ["O_W_ID", "O_D_ID"], ["O_ID"]],
            2: ["select", ["O_CARRIER_ID"], ["O_ID"]],
            3: ["select", ["O_OL_CNT"], ["O_ID", "O_W_ID", "O_D_ID"]],
            4: ["update", [], ["O_CARRIER_ID", "O_ID"]],
        },
        "ORDER_LINE": {
            1: ["select", ["OL_I_ID", "OL_SUPPLY_W_ID", "OL_DELIVERY_D", "OL_QUANTITY", "OL_DIST_INFO"], ["OL_O_ID", "OL_D_ID", "OL_W_ID"]],
            2: ["select", ["OL_D_ID", "OL_W_ID"], ["OL_O_ID"]],
            3: ["update", [], ["OL_DELIVERY_D", "OL_DIST_INFO", "OL_O_ID", "OL_D_ID", "OL_W_ID", "OL_NUMBER"]],
        },
        "DISTRICT": {
            1: ["select", ["D_STREET_1", "D_STREET_2", "D_CITY", "D_STATE", "D_ZIP"], ["D_ID"]],
            2: ["select", ["D_W_ID"], ["D_ID"]],
            3: ["select", ["D_ID", "D_NAME"], ["D_CITY"]],
            4: ["select", ["D_ID", "D_NAME"], ["D_STATE"]],
            5: ["insert", [], ["D_ID", "D_W_ID", "D_NAME", "D_STREET_1", "D_STREET_2", "D_CITY", "D_STATE", "D_ZIP", "D_TAX", "D_YTD", "D_NEXT_O_ID"]],
            6: ["update", [], ["D_NAME", "D_STREET_1", "D_STREET_2", "D_CITY", "D_STATE", "D_ZIP", "D_ID", "D_W_ID"]],
            7: ["delete", [], ["D_ID", "D_W_ID", "D_NAME"]],
        },
        "ITEM": {
            1: ["select", ["I_IM_ID", "I_NAME", "I_PRICE", "I_DATA"], ["I_ID"]],
            2: ["update", [], ["I_NAME", "I_PRICE", "I_DATA", "I_ID"]],
            3: ["insert", [], ["I_ID", "I_IM_ID", "I_NAME", "I_PRICE", "I_DATA"]],
            4: ["delete", [], ["I_ID"]],
        },
        "CUSTOMER": {
            1: ["select", ["C_STREET_1", "C_STREET_2", "C_CITY", "C_STATE", "C_ZIP", "C_PHONE"], ["C_W_ID", "C_D_ID", "C_ID"]],
        },
    },

    "FinancialMan": {
        "HISTORY": {
            1: ["select", ["H_AMOUNT"], ["H_C_ID", "H_DATE", "H_DATE"]],
            2: ["select", ["H_AMOUNT"], ["H_C_ID", "H_DATE", "H_DATE"]],
            3: ["select", ["H_AMOUNT"], ["H_C_D_ID", "H_DATE", "H_DATE"]],
            4: ["select", ["H_AMOUNT"], ["H_C_D_ID", "H_DATE", "H_DATE"]],
            5: ["select", ["H_AMOUNT"], ["H_W_ID", "H_DATE", "H_DATE"]],
            6: ["select", ["H_AMOUNT"], ["H_W_ID", "H_DATE", "H_DATE"]],
            7: ["update", [], ["H_AMOUNT", "H_DATA", "H_C_ID", "H_C_D_ID", "H_C_W_ID"]],
            8: ["delete", [], ["H_C_ID", "H_C_D_ID", "H_W_ID"]],
        },
        "ORDERS": {
            1: ["select", ["O_C_ID"], ["O_W_ID", "O_D_ID", "O_ID"]],
            2: ["select", ["O_CARRIER_ID"], ["O_W_ID", "O_D_ID", "O_ID"]],
            3: ["select", ["O_ID", "O_CARRIER_ID"], ["O_W_ID", "O_D_ID", "O_ID"]],
            4: ["select", ["O_OL_CNT"], ["O_W_ID", "O_D_ID", "O_ID"]],
            5: ["select", ["O_W_ID", "O_D_ID"], ["O_ID"]],
            6: ["insert", ["O_ENTRY_D", ], ["O_W_ID", "O_D_ID", "O_ID", "O_C_ID", "O_OL_CNT", "O_ALL_LOCAL", "O_CARRIER_ID"]],
            7: ["update", [], ["O_CARRIER_ID", "O_W_ID", "O_D_ID", "O_ID"]],
            8: ["delete", [], ["O_W_ID", "O_D_ID", "O_ID"]],
        },
        "ORDER_LINE": {
            1: ["select", ["OL_AMOUNT"], ["OL_O_ID", "OL_D_ID", "OL_W_ID"]],
            2: ["select", ["OL_QUANTITY"], ["OL_O_ID", "OL_DELIVERY_D", "OL_DELIVERY_D"]],
            3: ["select", ["OL_AMOUNT"], ["OL_DELIVERY_D", "OL_DELIVERY_D"]],
        },
        "CUSTOMER": {
            1: ["select", ["C_FIRST", "C_LAST", "C_PHONE"], ["C_W_ID", "C_D_ID", "C_ID"]],
            2: ["select", ["C_CREDIT", "C_CREDIT_LIM"], ["C_W_ID", "C_D_ID", "C_ID"]],
            3: ["select", ["C_CREDIT_LIM", "C_DISCOUNT"], ["C_W_ID", "C_D_ID", "C_ID"]],
            4: ["select", ["C_SINCE", "C_YTD_PAYMENT"], ["C_W_ID", "C_D_ID", "C_ID"]],
            5: ["select", ["C_YTD_PAYMENT", "C_PAYMENT_CNT", "C_BALANCE"], ["C_W_ID", "C_D_ID", "C_ID"]],
            6: ["update", [], ["C_CREDIT", "C_CREDIT_LIM", "C_W_ID", "C_D_ID", "C_ID"]],
            7: ["update", [], ["C_DISCOUNT", "C_W_ID", "C_D_ID", "C_ID"]],
        },
        "STOCK": {
            1: ["select", ["S_QUANTITY", "S_ORDER_CNT"], ["S_W_ID", "S_I_ID"]],
            2: ["select", ["S_I_ID", "S_QUANTITY", "S_REMOTE_CNT"], ["S_W_ID"]],
            3: ["select", ["S_QUANTITY", "S_ORDER_CNT", "S_REMOTE_CNT"], ["S_I_ID", "S_W_ID"]],
            4: ["select", ["S_YTD"], ["S_W_ID", "S_I_ID"]],
        }, 
        "ITEM": {
            1: ["select", ["I_PRICE"], ["I_ID"]],
        }, 
        "WAREHOUSE": {
            1: ["select", ["W_NAME", "W_YTD"], ["W_ID"]],
            2: ["select", ["W_NAME", "W_TAX"], ["W_ID"]],
            3: ["select", ["W_STREET_1", "W_STREET_2", "W_CITY", "W_STATE", "W_ZIP"], ["W_ID"]],
            4: ["update", [], ["W_TAX", "W_YTD", "W_ID"]],
        }, 
        "DISTRICT": {
            1: ["select", ["D_NAME", "D_YTD"], ["D_ID"]],
            2: ["select", ["D_NAME", "D_TAX"], ["D_ID"]],
            3: ["select", ["D_STREET_1", "D_STREET_2", "D_CITY", "D_STATE", "D_ZIP"], ["D_W_ID", "D_ID"]],
            4: ["update", [], ["D_TAX", "D_YTD", "D_ID", "D_W_ID"]],
        },
    },
}